# -*- coding: utf-8 -*-
"""Bài 23.6 - Huỳnh Tuyên Chương 31251021888

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lWwHK_Eg1pepKK8ODmIvpqKclYa6RUUs
"""

!pip install osmnx networkx

import osmnx as ox
import networkx as nx
place = "Binh Tan, Ho Chi Minh City"
g = ox.graph_from_place(place, network_type="drive")
ox.plot_graph(g, node_size = 10, edge_color = "blue", edge_linewidth=0.5)
stats = ox.basic_stats(g)
print("Số lượng nút giao:", stats["n"])
print("Số lượng cạnh:", stats["m"])
print("Chiều dài trung bình đường (m):", stats["edge_length_avg"])
print("Tổng chiều dài đường (km):", stats["edge_length_total"]/1000)
print("Mật độ mạng (km đường/km²):", stats["edge_density_km"])

"""Quy hoạch giao thông: giúp mô phỏng luồng xe, giảm ùn tắc.
Logistics & vận tải: tối ưu tuyến đường giao hàng, giảm chi phí.
Ứng dụng AI: dữ liệu mạng là đầu vào cho các mô hình dự đoán lưu lượng, phân tích hành vi di chuyển, và hệ thống xe tự lái.
Quản lý đô thị: hỗ trợ ra quyết định về mở rộng hạ tầng, phân bổ nguồn lực.
"""

