# -*- coding: utf-8 -*-
"""Bài 23.5 - Huỳnh Tuyên Chương 31251021888

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y3UAwgVa3wv1b8u1ak9z78JT1toC2tSk
"""

import folium
warehouses = {
    "Kho A": {"loc":[10.767, 106.623], "radius": 1000},
    "Kho B": {"loc":[10.790, 106.710], "radius": 2000},
    "Kho C": {"loc":[10.760, 106.690], "radius": 5500}
}
m = folium.Map(location=[10.776, 106.700], zoom_start=13)
for name, data in warehouses.items():
    folium.Marker(data["loc"], popup=name, icon=folium.Icon(color="green")).add_to(m)
    folium.Circle(data["loc"], radius=data["radius"], color="blue", fill=True,fill_opacity=0.1).add_to(m)
m

"""vùng bán kính 1km: phù hợp giao hàng nội thành, chi phí thấp
vùng bán kính 3km: mở rộng phạm vi nhưng vẫn đảm bảo được tốc độ giao hàng, chi phí có sự thay đổi nhỏ, không đáng kể
vùng có bán kính 5,5km: phạm vi giao hàng rất rộng, chi phí và thời gian giao hàng tăng

Nếu mục tiêu là giao nhanh, chi phí thấp → tập trung vùng 1-3 km.
Nếu mục tiêu là mở rộng thị trường → kết hợp cả 10 km nhưng cần tối ưu tuyến đường và phương tiện.
Có thể áp dụng mô hình đa kho: mỗi kho phụ trách phạm vi 3-5 km để giảm chi phí và tăng tốc độ.
"""

