# -*- coding: utf-8 -*-
"""Bài 23.2 - Huỳnh Tuyên Chương 31251021888

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eZUQosNTuVeiqZtvRWm3-klWlDvWBOVE
"""

from geopy.distance import geodesic
#công viên 23/9 - điểm trung tâm
a = (10.7695, 106.6930)
#Đại học kinh tế co sở A
b = (10.7830, 106.6949)
# Bệnh viện Chợ Rẫy
c = (10.7567, 106.6597)
# Thảo Cầm Viên Sài Gòn
d = (10.7906, 106.7053)
# Chợ Bến Thành
e = (10.7725, 106.6980)
# Landmark 81
f = (10.7940, 106.7217)
# Địa đạo Củ Chi
g = (11.0630, 106.5291)
# Bảo tàng Mỹ thuật TP.HCM
h = (10.7699, 106.6992)
# Bến Bạch Đằng
i = (10.7764, 106.7069)
# Nhà thờ Đức Bà
j = (10.7792, 106.6992)
# Dinh Độc Lập
k = (10.7770, 106.6955)
distance_ab = geodesic(a,b).km
distance_ac = geodesic(a,c).km
distance_ad = geodesic(a,d).km
distance_ae = geodesic(a,e).km
distance_af = geodesic(a,f).km
distance_ag = geodesic(a,g).km
distance_ah = geodesic(a,h).km
distance_ai = geodesic(a,i).km
distance_aj = geodesic(a,j).km
distance_ak = geodesic(a,k).km
print(f"Khoảng cách thực tế: {distance_ab} km")
print(f"Khoảng cách thực tế: {distance_ac} km")
print(f"Khoảng cách thực tế: {distance_ad} km")
print(f"Khoảng cách thực tế: {distance_ae} km")
print(f"Khoảng cách thực tế: {distance_af} km")
print(f"Khoảng cách thực tế: {distance_ag} km")
print(f"Khoảng cách thực tế: {distance_ah} km")
print(f"Khoảng cách thực tế: {distance_ai} km")
print(f"Khoảng cách thực tế: {distance_aj} km")
print(f"Khoảng cách thực tế: {distance_ak} km")

import folium
m = folium.Map(location=[10.7695, 106.6930], zoom_start=13)
folium.Marker([10.7695, 106.6930], popup="công viên 23/9", tooltip="Click vào").add_to(m)
folium.Marker([10.7830, 106.6949], popup="đại học kinh tế", tooltip="Click vào").add_to(m)
folium.Marker([10.7906, 106.7053], popup="thảo cầm viên", tooltip="Click vào").add_to(m)
folium.Marker([10.7725, 106.6980], popup="chợ bến thành", tooltip="Click vào").add_to(m)
folium.Marker([10.7940, 106.7217], popup="landmark 81", tooltip="Click vào").add_to(m)
folium.Marker([11.0630, 106.5291], popup="địa đọa củ chi", tooltip="Click vào").add_to(m)
folium.Marker([10.7699, 106.6992], popup="bảo tàng mỹ thuật", tooltip="Click vào").add_to(m)
folium.Marker([10.7792, 106.6992], popup="nhà thờ đức bà", tooltip="Click vào").add_to(m)
folium.Marker([10.7764, 106.7069], popup="bến bạch đằng", tooltip="Click vào").add_to(m)
folium.Marker([10.7567, 106.6597], popup="bệnh viện chợ rẫy", tooltip="Click vào").add_to(m)
folium.Marker([10.7770, 106.6955], popup="dinh độc lập", tooltip="Click vào").add_to(m)
folium.PolyLine([[10.7695, 106.6930], [10.7830, 106.6949]], color="blue").add_to(m)
folium.PolyLine([[10.7695, 106.6930], [10.7567, 106.6597]], color="red").add_to(m)
folium.PolyLine([[10.7695, 106.6930], [10.7906, 106.7053]], color="yellow").add_to(m)
folium.PolyLine([[10.7695, 106.6930], [10.7725, 106.6980]], color="pink").add_to(m)
folium.PolyLine([[10.7695, 106.6930], [10.7940, 106.7217]], color="black").add_to(m)
folium.PolyLine([[10.7695, 106.6930], [11.0630, 106.5291]], color="gray").add_to(m)
folium.PolyLine([[10.7695, 106.6930], [10.7699, 106.6992]], color="green").add_to(m)
folium.PolyLine([[10.7695, 106.6930], [10.7764, 106.7069]], color="purple").add_to(m)
folium.PolyLine([[10.7695, 106.6930], [10.7770, 106.6955]], color="brown").add_to(m)
folium.PolyLine([[10.7695, 106.6930], [10.7792, 106.6992]], color="brown").add_to(m)
m

