# -*- coding: utf-8 -*-
"""Bài 23.8 - Huỳnh Tuyên Chương 31251021888

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uVUYnsMX8TU_oo1GXjrdGG79clEtS5Ww
"""

import folium
from geopy.distance import geodesic
customers = {
    "Khách 1": (10.7620, 106.6820),
    "Khách 2": (10.8050, 106.6400),
    "Khách 3": (10.8300, 106.6700)
}

drivers = {
    "Xe 1": (10.7700, 106.7000),
    "Xe 2": (10.8100, 106.7200),
    "Xe 3": (10.8450, 106.6500)
}

speed_kmh = 30.0  # tốc độ xe trung bình được định sẵn
chuyến = []
used_drivers = set()

for cname, cloc in customers.items():
    metrics = {}
    for dname, dloc in drivers.items():
        if dname not in used_drivers:
            dist = geodesic(cloc, dloc).km
            time_h = dist / speed_kmh
            metrics[dname] = (dist, time_h)
    chosen_driver = min(metrics, key=lambda x: metrics[x][1])
    dist, time_h = metrics[chosen_driver]
    chuyến.append((cname, cloc, chosen_driver, drivers[chosen_driver], dist, time_h))
    used_drivers.add(chosen_driver)
print("Kết quả ghép khách – xe:")
for cname, _, dname, _, dist, time_h in chuyến:
    print(f"{cname} ⇄ {dname} | Khoảng cách: {dist:.2f} km | Thời gian: {time_h*60:.1f} phút")

m = folium.Map(location=(10.7900, 106.6900), zoom_start=12)

for cname, cloc in customers.items():
    folium.Marker(cloc, popup=cname, icon=folium.Icon(color="red")).add_to(m)

for dname, dloc in drivers.items():
    folium.Marker(dloc, popup=dname, icon=folium.Icon(color="green")).add_to(m)

for cname, cloc, dname, dloc, dist, time_h in chuyến:
    folium.PolyLine([cloc, dloc], color="purple", weight=3,
                    tooltip=f"{cname} ⇄ {dname}\nKhoảng cách: {dist:.2f} km\nThời gian: {time_h*60:.1f} phút").add_to(m)

# Xuất bản đồ
m

