# -*- coding: utf-8 -*-
"""bài 23.3 - Huỳnh Tuyên Chương 31251021888

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14JXGYP9_2WzpDjhJr_m4lwMDLthdFqmM
"""

import folium
from folium.plugins import HeatMap
import random
center = [10.7769, 106.7009]
data = []
for _ in range(30):
    latitude = 10.76 + random.uniform(-0.05, 0.05)
    longitude = 106.70 + random.uniform(-0.05, 0.05)
    data.append([latitude, longitude])
m = folium.Map(location=center, zoom_start=13)
HeatMap(data, radius=15).add_to(m)
m

"""những vùng nóng là nơi tạp trung nhiều khách hàng, cần tăng nhân lực, đẩy mạnh vai trò marketing và mở thêm điểm giao dịch

những vùng lạnh là những nơi ít khách hàng, nên cân nhắc kiểm soát nhân lực, giảm chi phí hoặc tăng cường quảng bá để thu hút thêm khách hàng
"""

