# -*- coding: utf-8 -*-
"""Bài 23.12 - Huỳnh Tuyên Chương 31251021888

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s0G1XI7XffZ6bemxIDdYTmun9LC8qFTZ
"""

import folium
from geopy.distance import geodesic
import itertools
def best_route(start_point, customers):
    # Tính khoảng cách từ kho đến từng khách
    distances = {name: geodesic(start_point, coord).km for name, coord in customers.items()}
    print("Khoảng cách từ kho đến từng khách hàng:")
    for name, dist in distances.items():
        print(f"{name}: {dist:.2f} km")

    # Tìm tuyến tối ưu bằng brute force
    min_route, min_dist = None, float('inf')
    for perm in itertools.permutations(customers.items()):
        route = [start_point] + [p[1] for p in perm]
        total = sum(geodesic(route[i], route[i+1]).km for i in range(len(route)-1))
        if total < min_dist:
            min_dist, min_route = total, perm

    print("Thứ tự giao hàng tối ưu:")
    for i, (name, _) in enumerate(min_route, 1):
        print(f"{i}. {name}")
    print(f"Tổng khoảng cách: {min_dist:.2f} km\n")

    return [start_point] + [loc for _, loc in min_route]

# --- Dữ liệu ---
routes_data = [
    {
        "start_point": (10.7769, 106.7009), #phường sài gòn
        "customers": {
            "Khách 1": (10.7900, 106.7000),
            "Khách 2": (10.7800, 106.7200),
            "Khách 3": (10.7700, 106.6800)
        }
    },
    {
        "start_point": (10.8535, 106.6280),  #quận 12 cũ
        "customers": {
            "Khách 4": (10.8531, 106.6405),
            "Khách 5": (10.8536, 106.6279),
            "Khách 6": (10.8574, 106.6427)
        }
    },
    {
        "start_point": (10.8015, 106.6527),  #quận tân bình
        "customers": {
            "Khách 4": (10.8018,	106.6529),
            "Khách 5": (10.8012,	106.6535),
            "Khách 6": (10.7907, 106.6641)
        }
    }
]

# --- Vẽ bản đồ ---
m = folium.Map(location=(10.7769, 106.7009), zoom_start=12)

colors = ["red", "blue", "green", "purple"]  # nhiều tuyến thì thêm màu
for idx, data in enumerate(routes_data):
    route_coords = best_route(data["start_point"], data["customers"])
    folium.Marker(data["start_point"], popup=f"Kho {idx+1}",
                  icon=folium.Icon(color="green")).add_to(m)
    for name, loc in data["customers"].items():
        folium.Marker(loc, popup=name, icon=folium.Icon(color="blue")).add_to(m)
    folium.PolyLine(route_coords, color=colors[idx % len(colors)], weight=3).add_to(m)

m

