# -*- coding: utf-8 -*-
"""Bài 23.7 - Huỳnh Tuyên Chương 31251021888

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VSi-3FhkVf1jIeGte5C0tcDyvBvVPZx-
"""

!pip install osmnx networkx

import osmnx as ox
import networkx as nx
place = "Binh Tan, Ho Chi Minh City, Vietnam"
G = ox.graph_from_place(place, network_type="drive")
origin = (10.7747, 106.6985)   # công viên Tao Đàn
destination = (10.7733, 106.6595)  # Đại học Bách Khoa
orig_node = ox.distance.nearest_nodes(G, origin[1], origin[0])
dest_node = ox.distance.nearest_nodes(G, destination[1], destination[0])

route_AStar =  nx.astar_path(G, orig_node, dest_node, weight="length")# A*
ox.plot_graph_route(G, route_AStar, route_color="blue", route_linewidth=3, node_size=0)

import osmnx as ox
import networkx as nx
place = "Binh Tan, Ho Chi Minh City, Vietnam"
G = ox.graph_from_place(place, network_type="drive")
origin = (10.7747, 106.6985)   # công viên Tao Đàn
destination = (10.7733, 106.6595)  # Đại học Bách Khoa
orig_node = ox.distance.nearest_nodes(G, origin[1], origin[0])
dest_node = ox.distance.nearest_nodes(G, destination[1], destination[0])

route_dijkstra =  nx.shortest_path(G, orig_node, dest_node, weight="length", method="dijkstra")
ox.plot_graph_route(G, route_dijkstra, route_color="red", route_linewidth=3, node_size=0)

"""giữa A* và Dijkstra thì A* cho ra kết quả nhanh hơn
code tìm đường ngắn nhất của A* gọn hơn cú pháp "method" của Dijkstra
"""

