# -*- coding: utf-8 -*-
"""Bài 23.1 - Huỳnh Tuyên Chương 31251021888

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tfZ3LIJ7BT_ByScTtAysCAPAhlLRul6H

print('hello')
"""

from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent = "geoapi")
location= geolocator.geocode("Nha Tho Duc Ba, Ho Chi Minh City")
print(f"tọa độ nha hat thanh pho :{location.latitude}, {location.longitude}")

m = folium.Map(location=[10.7770348, 106.695488], zoom_start=13)
folium.Marker([10.7770348, 106.695488], popup = "Dinh Độc Lập", tooltip = "Click").add_to(m)
folium.Marker([10.7830141, 106.6948927], popup= "Đại Học Kinh Tế Cơ sở A", tooltip = "Click").add_to(m)
folium.Marker([10.7826372, 106.6959464], popup= "Hồ con Rùa", tooltip = "Click").add_to(m)
folium.Marker([10.7816448, 106.6947138], popup= "Trường Đại học Kiến trúc TPHCM", tooltip = "Click").add_to(m)
folium.Marker([10.7767437, 106.7032488], popup= "Nhà hát Thành Phố", tooltip = "Click").add_to(m)
folium.Marker([10.7792374, 106.6991514], popup= "Nhà thờ Đức Bà", tooltip = "Click").add_to(m)
m

